# Generated by Django 6.0.3 on 2026-03-25 14:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="First Name"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Last Name"),
                ),
                ("birth_date", models.DateField(verbose_name="Birth Date")),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")],
                        default="M",
                        max_length=10,
                        verbose_name="Gender",
                    ),
                ),
                (
                    "current_academic_level",
                    models.CharField(
                        choices=[
                            ("p1", "Primary 1"),
                            ("p2", "Primary 2"),
                            ("p3", "Primary 3"),
                            ("p4", "Primary 4"),
                            ("p5", "Primary 5"),
                            ("p6", "Primary 6"),
                            ("s1", "Secondary 1"),
                            ("s2", "Secondary 2"),
                            ("s3", "Secondary 3"),
                            ("s4", "Secondary 4"),
                            ("s5", "Secondary 5"),
                            ("s6", "Secondary 6"),
                        ],
                        max_length=10,
                        verbose_name="Current Academic Level",
                    ),
                ),
                (
                    "enrollment_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("transfer", "Transfer"),
                            ("dismissed", "Dismissed"),
                            ("graduated", "Graduated"),
                        ],
                        max_length=20,
                        verbose_name="Enrollment Status",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="students/photos",
                        verbose_name="photo",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
