# Generated by Django 6.0.3 on 2026-03-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="enrollment_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("transferred", "Transferred"),
                    ("dismissed", "Dismissed"),
                    ("graduated", "Graduated"),
                ],
                max_length=20,
                verbose_name="Enrollment Status",
            ),
        ),
    ]
