# Generated by Django 6.0.3 on 2026-05-21 06:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_management", "0002_alter_student_enrollment_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Course Name"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Course Code"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "academic_level",
                    models.CharField(
                        choices=[
                            ("p1", "Primary 1"),
                            ("p2", "Primary 2"),
                            ("p3", "Primary 3"),
                            ("p4", "Primary 4"),
                            ("p5", "Primary 5"),
                            ("p6", "Primary 6"),
                            ("s1", "Secondary 1"),
                            ("s2", "Secondary 2"),
                            ("s3", "Secondary 3"),
                            ("s4", "Secondary 4"),
                            ("s5", "Secondary 5"),
                            ("s6", "Secondary 6"),
                        ],
                        max_length=10,
                        verbose_name="Academic Level",
                    ),
                ),
                ("credits", models.IntegerField(default=3, verbose_name="Credits")),
                (
                    "instructor",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Instructor Name",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("archived", "Archived"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="StudentCourse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "enrollment_date",
                    models.DateField(auto_now_add=True, verbose_name="Enrollment Date"),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "A (90-100)"),
                            ("B", "B (80-89)"),
                            ("C", "C (70-79)"),
                            ("D", "D (60-69)"),
                            ("F", "F (Below 60)"),
                            ("", "Not Graded"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Grade",
                    ),
                ),
                (
                    "score",
                    models.FloatField(blank=True, null=True, verbose_name="Score"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("dropped", "Dropped"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="students",
                        to="student_management.course",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="courses",
                        to="student_management.student",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrollment_date"],
                "unique_together": {("student", "course")},
            },
        ),
    ]
